"""empty message

Revision ID: 00db9dea390e
Revises: 7481f8468439
Create Date: 2023-11-27 14:02:55.620344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00db9dea390e'
down_revision = '7481f8468439'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usedtoken', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'usedtoken', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usedtoken', type_='foreignkey')
    op.drop_column('usedtoken', 'user_id')
    # ### end Alembic commands ###
