"""empty message

Revision ID: 413729f35d9b
Revises: dcdb2896b165
Create Date: 2023-11-27 13:53:10.756550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413729f35d9b'
down_revision = 'dcdb2896b165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
