"""Add deposit c2c table

Revision ID: 518fbbd3f95d
Revises: b61c75b472e8
Create Date: 2023-01-10 12:03:49.205243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518fbbd3f95d'
down_revision = 'b61c75b472e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depositrecords',
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('fiat_type', sa.String(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('counter_party', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('order_created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('order_number')
    )
    op.create_index(op.f('ix_depositrecords_order_number'), 'depositrecords', ['order_number'], unique=False)
    op.create_index(op.f('ix_depositrecords_order_type'), 'depositrecords', ['order_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_depositrecords_order_type'), table_name='depositrecords')
    op.drop_index(op.f('ix_depositrecords_order_number'), table_name='depositrecords')
    op.drop_table('depositrecords')
    # ### end Alembic commands ###
