"""por

Revision ID: 8b3d58fc01df
Revises: b52211b96dab
Create Date: 2023-11-27 13:35:09.453397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3d58fc01df'
down_revision = 'b52211b96dab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
