"""empty message

Revision ID: ab5e26003f67
Revises: 00db9dea390e
Create Date: 2023-11-27 14:05:52.243744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5e26003f67'
down_revision = '00db9dea390e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usedtoken', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usedtoken', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
