"""por

Revision ID: b52211b96dab
Revises: dfe743849802
Create Date: 2023-11-27 13:33:53.145198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52211b96dab'
down_revision = 'dfe743849802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('depositrecords', 'order_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('depositrecords', 'asset_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('depositrecords', 'fiat_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('depositrecords', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depositrecords', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depositrecords', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('depositrecords', 'exchange_rate',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('depositrecords', 'order_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('depositrecords', 'order_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('depositrecords', 'exchange_rate',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('depositrecords', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depositrecords', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depositrecords', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('depositrecords', 'fiat_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('depositrecords', 'asset_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('depositrecords', 'order_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
