"""empty message

Revision ID: dcdb2896b165
Revises: 8b3d58fc01df
Create Date: 2023-11-27 13:52:46.369654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdb2896b165'
down_revision = '8b3d58fc01df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
